default:
  image: node:20.10.0

variables: # Define any environment variables needed for your CI/CD pipeline

cache:
  paths:
    - node_modules/
    - .next/cache/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build

test:
  stage: test
  script:
    - npm install
    - npm run test

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --archive=tgz --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - production
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --archive=tgz --token=$VERCEL_TOKEN
